---
- hosts: all
  become: yes
  tasks:
    - name: i want to install ubuntu on node
      apt:
        name: git
        state: present

    - name: install tree on ubuntu nodes
      apt:
        name: tree
        state: absent

    - name: install wget on ubuntu nodes
      apt:
        name: wget
        state: absent
