---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: i want to install webserver on only ansible ubuntu node
      apt:
        name: apache2
        state: present
      when: ansible_os_family =="Debian"
    - name: i want to start webserver on ansible ubuntu node
      service:
        name: apache2
        state: started
      when: ansible_os_family =="Debian"

    - name: i want to install webserver on only ansible Redhat node
      yum:
        name: httpd
        state: present
      when: ansible_os_family =="RedHat"

    - name: i want to start webserver on only ansible Redhat node
      service:
        name: httpd
        state: started
      when: ansible_os_family =="RedHat"
